name: opentype
version: 0.1.0
description: An OpenType and TrueType font parser and writer
author: José Luis Cruz <joseluis@andamira.net>
homepage: https://github.com/joseluis/opentype.dart/
environment:
  sdk: ">=1.13.1 <2.0.0"
dependencies:
  browser: "^0.10.0+2"
  js: "^0.6.0"
